SRCH-3046 update the i14y README to use search-services
GSA/i14y pull request #193
Opened 2022-06-12 21:55 UTC by danswick

## Summary
- Updates to README:
  * Describe new `search-services` method for starting relevant services.
  * Move service-specific instructions to the search-services README:
    * [ ] TODO: Create PR for search-services docs and link here.
- Delete docker/docker compose files.
- Made minor version bumps in circle config.
- Minor env variable tweak to match other repos: `ES_HOST` --> `ES_HOSTS`
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review:
 
#### Functionality Checks
 
- [x] Code is functional.

- [ ] Automated checks pass. If CodeClimate checks do not pass, explain reason for failures:

- [ ] If your changes will be tested manually, you have run `bundle update` and committed your changes to Gemfile.lock.
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
 
- [ ] Your target branch is `main` or `production`, or you have specified the reason for an alternate branch here:
 
- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] You have squashed your commits into a single commit (exceptions: your PR includes commits with formatting-only changes, such as required by Rubocop or Cookstyle, or if this is a feature branch that includes multiple commits)
 
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket
 
#### Process Checks

- [ ] You have specified an "Assignee", and if necessary, additional reviewers

2022-06-12 22:07 UTC, danswick commented on README.md
> +The Elasticsearch services provided by `searchgov-services` is configured to run on the default port, [9200](http://localhost:9200/). To use a different host (with or without port) or set of hosts, s
When would someone want to override the default port? Are there scenarios other than testing with Elasticsearch 7 running on `9207`?

2022-06-12 22:08 UTC, danswick commented on config/elasticsearch.yml
> +    - <%= ENV['ES_HOSTS'] || 'localhost:9200' %>
Made this plural to match [`search-gov`](https://github.com/GSA/search-gov/blob/e285f8a54b44694cefd781f01c0be084726dec98/config/secrets.yml.dev#L61).

2022-06-21 15:55 UTC, MothOnMars commented
@danswick , can you complete the remaining checklist items? If an item doesn't apply or is not nececessary (such as merging recent changes from `main`, when there aren't any), you can check the box and add an "N/A" to the checklist item.

2022-06-28 16:26 UTC, danswick commented
@MothOnMars PR checklist has been updated!

2022-07-01 18:51 UTC, lorawoodford requested changes
@danswick Same small typo as search-gov.

2022-07-01 18:51 UTC, lorawoodford commented on README.md
> +Verify that Elasticsearch 6.8.x is running on port the expected port (in this example, port 9200):
```suggestion
Verify that Elasticsearch 6.8.x is running on the expected port (port 9200 by default):
```

2022-07-05 15:51 UTC, lorawoodford approved these changes
LGTM

2022-07-05 18:53 UTC, merged