[SRCH-3351] language support for built-in languages (Hindi and Bengali)
GSA/i14y pull request #205
Opened 2022-09-20 03:55 UTC by danswick

## Summary
- Brief summary of the changes included in this PR
- Any additional information or context which may help the reviewer
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks

- [ ] You have run `bundle update` and committed your changes to Gemfile.lock.
 
- [ ] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [ ] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [ ] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
- [ ] Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
 
#### Process Checks

- [ ] You have specified at least one "Reviewer".

2022-09-26 21:52 UTC, danswick commented on app/templates/documents.rb
> +  LIGHT_STEMMERS = { fr: 'french', de: 'german', es: 'spanish', it: 'italian', pt: 'portuguese' }
Rubocop's rule, "Prefer single-quoted strings when you don't need string interpolation or special symbols."

2022-09-26 21:54 UTC, danswick commented on app/templates/documents.rb
> +  STANDARD_STEMMERS = { en: 'english', fi: 'finnish', hu: 'hungarian', ru: 'russian', sv: 'swedish', hi: 'hindi', bn: 'bengali' }
Rubocop also flagged these lines as "Freeze mutable objects assigned to constants," but I'm not sure if we want to do that here.

2022-09-26 21:59 UTC, danswick commented
@MothOnMars happy to discuss any of the changes here! I made a couple of inline comments about Rubocop issues and am also not totally sure if my approach for testing languages is well-aligned with Ruby conventions.

2022-09-27 13:40 UTC, MothOnMars commented
@danswick , I'll start looking at this, but can you update the PR so that all the checklist tasks are completed?

2022-09-27 14:51 UTC, MothOnMars requested changes
@danswick , I have a few requested changes.

For now, I think these specs are sufficient for the purposes of this story. They can be fleshed out and refined as we add more languages, but these test what they need to test, and result in readable spec output, so they are fine for now. 

The structure of the spec (iterating over an assigned array) is a little wonky, but at this point in time, I don't have a better way to do this. We could probably use [shared examples](https://relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples) for this, but I think your version may be more readable. I'll noodle a bit more, but for now let's just stick with what's sufficient and (mostly) done.

2022-09-27 14:51 UTC, MothOnMars commented on spec/classes/document_search_spec.rb
> +                             description: "description #{lang_name}",
I would remove `created`, `title` and `description`, as these are not being used by the spec.

2022-09-27 20:49 UTC, danswick commented on spec/classes/document_search_spec.rb
> +        expect(document_search_results.results.first['content']).to match(/#{lang[:query]}/)
Good point! I think makes sense to reduce this down to just one expectation. The test case is pretty limited and the first two expectations don't really add any useful information as far as I can tell: the value of `content` should break expectations if there are 0 documents and we already have examples for the language parameter/filter.

2022-09-27 20:51 UTC, danswick commented on config/initializers/locales.rb
> +LANGUAGE_ANALYZER_LOCALES = [:bn, :de, :en, :es, :fi, :fr, :hi, :hu, :it, :ja, :ko, :pt, :ru, :sv, :zh]
Only `:hi` and `:bn` were added. The other changes on this line are just from alphabetization.

2022-09-28 14:13 UTC, MothOnMars approved these changes
LGTM

2022-10-13 17:49 UTC, merged